export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
export const CHANGE_HOT_RECOMMEND = "recommend/CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'

export const CHANGE_UP_RANKING = "recommend/CHANGE_UP_RANKING";
export const CHANGE_NEW_RANKING = "recommend/CHANGE_New_RANKING";
export const CHANGE_ORIGIN_RANKING = "recommend/CHANGE_ORIGIN_RANKING";


